### ISSUE TITLE
Downloading get stuck at some particular points

### ISSUE THREAD

**Issue by fgvfgfg564** [snap-research/Panda-70M#21]
I tried to download the dataset and it get stuck when I downloaded 13.1G files. The command line just get stuck with no updates, and network stat shows that it has also stopped. Have no idea about what happened. Perhaps some entry point in the csv file causes this?

I shuffled the csv file several times. Each time the stop point is different, ranging from 11G to 14G.

We have tried downloading on Windows and WSL, both leads to the same error. There's no problem with network or disk.

**Comment by tsaishien-chen** [comment]
Hi @fgvfgfg564, is there any error messages?

**Comment by fgvfgfg564** [comment]
There is no error message. The downloading process just simply got stuck there. We're guessing that perhaps some of the data points were too long and exceeded the upper limit of commands that windows can support, resulting in the error.

**Comment by Secant1998** [comment]
> Hi @fgvfgfg564, is there any error messages?

Hello, I am the co-worker of the questioner, thanks for your reply. There is no error message during the download and the same situation occurs in Ubuntu 22.04. However, our later tests revealed that CSV file was not the problem.

**Comment by kuno989** [comment]
The same error occurs.

**Comment by kuno989** [comment]
@tsaishien-chen
At first I thought it was a CPU usage issue, but it wasn't.
I tried running it with 64 cores 64GM RAM[instance] and 16 threads (on config file), and the CPU usage decreased from about 40 to 60 minutes before converging to 0%.
I didn't get any errors in the process.

@AliaksandrSiarohin @Secant1998 
Have you guys resolved the issue?

**Comment by tsaishien-chen** [comment]
Hi @fgvfgfg564, @Secant1998, @kuno989,
Sorry for your inconvenience. Which csv file were you downloading then?
Will the testing and validation set downloading also give you the same problem?
Also, when you killed the stuck process, did you notice which line does the process stuck at?

**Comment by kuno989** [comment]
Hi @tsaishien-chen 
I haven't exactly tested the issue I commented above, but I have logged usage when using video2dataset.
This can be due to too much data or poor memory or CPU management of video2dataset.

Here is a graph of usage when downloading the panda70m_training_full.csv data through Spark.
[OCPU: 64 (128) 158GB Ram] * 10 instance

```
subsampling: {}

reading:
    yt_args:
        download_size: 720 # I had the same issue at 480 resolution, so I don't think it's a quality issue.
        download_audio: True
        yt_metadata_args:
            writesubtitles:  True
            subtitleslangs: ['en']
            writeautomaticsub: True
            get_info: True
    timeout: 60
    sampler: null

storage:
    number_sample_per_shard: 100
    oom_shard_count: 5
    captions_are_subtitles: False

distribution:
    processes_count: 16
    thread_count: 16
    subjob_size: 10000
    distributor: "pyspark"
```

<img width="1240" alt="스크린샷 2024-03-21 오전 1 37 41" src="https://github.com/snap-research/Panda-70M/assets/87296378/33075bee-ccc5-4153-bcb1-2c489f54f764">

Usage of panda70m_testing.csv in the same configuration.

<img width="1243" alt="스크린샷 2024-03-21 오전 1 39 06" src="https://github.com/snap-research/Panda-70M/assets/87296378/48833945-14d8-4391-8a46-4ea541e4a564">
