### ISSUE TITLE
Silent mp4 files

### ISSUE THREAD

**Issue by VanderHua** [snap-research/Panda-70M#25]
Is the mp4 data downloaded through the script silent? 
I downloaded part of the training data through the provided script and found that the mp4 files were all silent. I confirmed that there was no problem with my device player.

**Comment by tsaishien-chen** [comment]
Hi @VanderHua,
Thanks for bringing this into attention! I am working on the support of audio downloading.
The code will be published tomorrow.

**Comment by VanderHua** [comment]
Great update! Thanks!

**Comment by kuno989** [comment]
Has this issue been resolved?

**Comment by tsaishien-chen** [comment]
Hi @kuno989,
Yes, the current codebase will download the video with audio by default. You can change the config file [here](https://github.com/snap-research/Panda-70M/blob/85a178ae961e51b0058ae3a4aba1dbf43521b813/dataset_dataloading/video2dataset/video2dataset/configs/panda_70M.yaml#L6) to download videos only if you want.

**Comment by kuno989** [comment]
Thanks @tsaishien-chen, I'll check it out!

**Comment by kuno989** [comment]
HI @tsaishien-chen .
I used the latest update version to work on it, but I still found that all the videos didn't contain sound.
Has anyone faced the same problem as me?

Below is the config.yaml I used.
```
subsampling: {}

reading:
    yt_args:
        download_size: 360
        download_audio: True
        yt_metadata_args:
            writesubtitles:  True
            subtitleslangs: ['en']
            writeautomaticsub: True
            get_info: True
    timeout: 60
    sampler: null

storage:
    number_sample_per_shard: 100
    oom_shard_count: 5
    captions_are_subtitles: False

distribution:
    processes_count: 32
    thread_count: 32
    subjob_size: 10000
    distributor: "pyspark"

```
