### ISSUE TITLE
Discrepancy in Expected vs. Actual Number of Video Clips Downloaded

### ISSUE THREAD

**Issue by pengzhiliang** [snap-research/Panda-70M#44]
Hello,

I’ve encountered an odd phenomenon where the amount of downloadable data appears to be significantly less than anticipated, potentially well below 70M.

Here are the details:

I downloaded the first 10,000 rows of a CSV file, which should contain approximately 187,111 video clips based on the following calculation: 70,723,513 / 3,779,764 * 10,000. These clips were to be downloaded using the `files` output_format, distributed into 100 subfolders, with each subfolder expected to contain about 1,871 video clips (calculated as 187,111 / 100).

However, upon counting the clips in each subfolder, I discovered only around 200 clips each, which is significantly lower than the expected 1,871. This discrepancy is puzzling, especially since the download success rate is notably high (>99%).

The Bash output is as follows:
```bash
xxx: /mnt/data/pandam70m/data/part_00001# ll 00000/*.mp4 |wc -l  
223  
  
xxx: /mnt/data/pandam70m/data/part_00001# ll 00000/*.json |wc -l  
225  # (success rate of clips is also high)
  
xxx: /mnt/data/pandam70m/data/part_00001# cat 00000_stats.json  
{  
    "count": 100,  
    "successes": 98,  
    "failed_to_download": 2,  
    "failed_to_subsample": 0,  
    "duration": 745.6420252323151,  
    "bytes_downloaded": 250422000,  
    "start_time": 1712764675.583739,  
    "end_time": 1712765421.2257643,  
    "status_dict": {  
        "success": 98,  
        "[Errno 2] No such file or directory: '/tmp/7ed953b1-50ca-4631-a2cf-5d388d2ad70a.mp4'": 1,  
        "[Errno 2] No such file or directory: '/tmp/578de3a9-0df1-4941-8aaf-1ccd29563093.mp4'": 1  
    }  
}  
```

Here is my configuration:
```YAML
subsampling: {}  
  
reading:  
    yt_args:  
        download_size: 360  
        download_audio: True  
        yt_metadata_args:  
            writesubtitles:  True  
            subtitleslangs: ['en']  
            writeautomaticsub: True  
            get_info: True  
    timeout: 60  
    sampler: null  
  
storage:  
    number_sample_per_shard: 100  
    oom_shard_count: 5  
    captions_are_subtitles: False  
  
distribution:  
    processes_count: 1  
    thread_count: 2  
    subjob_size: 10000  
    distributor: "multiprocessing"  
```

Would you be able to help me analyze what might be causing this issue? Your assistance would be greatly appreciated.
