### ISSUE TITLE
The downloaded videos are compressed to low quality

### ISSUE THREAD

**Issue by jianzongwu** [snap-research/Panda-70M#48]
https://github.com/snap-research/Panda-70M/assets/37370789/17ab95ee-f2fc-4cc4-8833-7f46f11d35e5
https://github.com/snap-research/Panda-70M/assets/37370789/bfd6ed24-ae35-4c43-97f6-6e55a7df15ba

Hello, I used the download script to download validation videos but found that they are compressed a lot and, as a result, of low quality. Do you have any idea about this? I guess this may be caused by YouTube compressing the videos when downloading.

Does anyone have the same issue as I do?

**Comment by tsaishien-chen** [comment]
Hi @jianzongwu,
Thanks for your interest in our dataset and sorry the late reply.
What is the resolution of the download video? You can set the target resolution [here](https://github.com/snap-research/Panda-70M/blob/main/dataset_dataloading/video2dataset/video2dataset/configs/panda70m.yaml).
You can also check the yt-dlp download format [here](https://github.com/snap-research/Panda-70M/blob/0502e886e70096f1c1666dca3680f64b34c5495b/dataset_dataloading/video2dataset/video2dataset/data_reader.py#L181-L186). I think the problem can be solved if you always download "the best video" (i.e., using "bv" tag)

**Comment by jianzongwu** [comment]
Hello, I tried to set the target resolution to 720p and 360p. The downloaded videos are as the resolution, but both have compressed patches.

How to use the 'bv' tag in the downloading script?

**Comment by jianzongwu** [comment]
https://github.com/snap-research/Panda-70M/assets/37370789/96d42462-32b8-434a-9fc1-259986d36e1f

I tried again to download a video in 720p. The downloaded video is 720x1280. However, it still severely compressed.

**Comment by tsaishien-chen** [comment]
Hi @jianzongwu,

Could you please try to run this command:
`yt-dlp -f "bv[ext=mp4]" "https://www.youtube.com/watch?v=gsnqXt7d1mU"`
and see whether the downloaded video has severe compression?

**Comment by jianzongwu** [comment]
Interestingly, it is not compressed. I followed your command and downloaded the sunrise video with `bv.` It successfully gave me a high-quality video with the largest resolution. No compression phenomenon was found.

I also downloaded the 360p version of this video by this command：
`yt-dlp -f "wv*[height>=360][ext=mp4]" "https://www.youtube.com/watch?v=gsnqXt7d1mU"`
It downloads the 360p video, and also no compression is found.

I notice a difference between my downloading previous times and this time. The compressed videos can not be identified and opened in VSCode. I must download the videos to my local machine and open it with MP4 player. However, the successfully downloaded videos without compression can be opened directly by VSCode.

So, the problem is in the codebase, where it calls yt-dlp and saves the videos?

**Comment by jianzongwu** [comment]
``` yaml
subsampling: {}

reading:
    yt_args:
        download_size: 360
        download_audio: False
        yt_metadata_args:
            writesubtitles: False
            subtitleslangs: ['en']
            writeautomaticsub: False
            get_info: False
    timeout: 60
    sampler: null

storage:
    number_sample_per_shard: 100
    oom_shard_count: 5
    captions_are_subtitles: False

distribution:
    processes_count: 32
    thread_count: 32
    subjob_size: 10000
    distributor: "multiprocessing"
```

This is my config.
